AllCops:
  Exclude:
    - 'bin/**/*'
    - 'webex_xml_api.gemspec'

Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
